/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package demo;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author kalamari
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        usrGeslo.setText("");
        usrName.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        usrName = new javax.swing.JTextField();
        usrGeslo = new javax.swing.JPasswordField();
        btnLog = new javax.swing.JButton();
        btnReg = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Login");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 54, -1, -1));
        getContentPane().add(usrName, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 154, 187, 33));
        getContentPane().add(usrGeslo, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 238, 187, 33));

        btnLog.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnLog.setText("Login");
        btnLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogActionPerformed(evt);
            }
        });
        getContentPane().add(btnLog, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 332, 125, 38));

        btnReg.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnReg.setText("registracija");
        btnReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegActionPerformed(evt);
            }
        });
        getContentPane().add(btnReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 331, 125, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Uporabniško ime");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 124, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("geslo");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 205, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/bg_spremeni.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-730, 0, 1160, 400));

        setSize(new java.awt.Dimension(366, 427));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogActionPerformed
                // TODO add your handling code here:
        String strVrstica;
        BufferedReader br = null;
        boolean prijavljen = false;
        String[] tabUser;
        String  strUs, strPass, strIm, strPriim;
        char[] tabelaGeslo;
        String strGeslo = "";

        try {

           
            br = new BufferedReader(new FileReader("src/datoteke/uporabniki.txt"));

            StaticVars.g_strUser = usrName.getText();

            tabelaGeslo = usrGeslo.getPassword();
            
            for (int i = 0; i < tabelaGeslo.length; i++) {
                strGeslo = strGeslo + tabelaGeslo[i];
            }

            StaticVars.g_strPassword = StaticVars.getMd5(strGeslo);

            while (br.ready()) {

                strVrstica = br.readLine();

                tabUser = strVrstica.split(" ");

               
                strUs = tabUser[0];
                strPass = tabUser[1];
                strIm = tabUser[2];
                strPriim = tabUser[3];

                System.out.println(StaticVars.g_strPassword);
                System.out.println(strPass);

                if (strUs.equals(StaticVars.g_strUser) && strPass.equals(StaticVars.g_strPassword)) {
                   
                    prijavljen = true;
                    
                    StaticVars.g_strIme = strIm;
                    StaticVars.g_strPriimek = strPriim;
                    break;
                }
            }
            br.close();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
            try {
                if (br != null) {
                    br.close();
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Napaka pri zapiranju datoteke!");
            } finally {
                try {
                    if (br != null) {
                        br.close();
                    }
                } catch (Exception e) {
                    Logger.getLogger(Registracija.class.getName()).log(Level.SEVERE, null, e);
                }
            }
        }

        if (prijavljen == false) {
            JOptionPane.showMessageDialog(this, "Napačno uporabniško ime ali geslo!");
        } else {
           
          new ZacetnaStran().setVisible(true);
          dispose();
        }
        //System.exit(0);
        usrName.setText("");
        usrGeslo.setText("");
    }//GEN-LAST:event_btnLogActionPerformed

    private void btnRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegActionPerformed
        new Registracija().setVisible(true);
    }//GEN-LAST:event_btnRegActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLog;
    private javax.swing.JButton btnReg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField usrGeslo;
    private javax.swing.JTextField usrName;
    // End of variables declaration//GEN-END:variables
}
