/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package demo;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author kalamari
 */
public class Registracija extends javax.swing.JFrame {

    /**
     * Creates new form Registracija
     */
    public Registracija() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        usrName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nameTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        priimekTxt = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        btnSpremeni = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        usrGeslo = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Registracija");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 26, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("uporabniško ime");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 101, 144, -1));
        getContentPane().add(usrName, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 146, 133, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("geslo");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 182, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ime");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 256, -1, -1));
        getContentPane().add(nameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 289, 130, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("priimek");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 337, -1, -1));
        getContentPane().add(priimekTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 377, 130, 30));

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 454, 106, 35));

        btnSpremeni.setText("spremeni");
        btnSpremeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSpremeniActionPerformed(evt);
            }
        });
        getContentPane().add(btnSpremeni, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 454, 106, 35));

        btnSave.setText("shrani");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 454, 104, 35));
        getContentPane().add(usrGeslo, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 215, 137, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/bg_spremeni.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-630, -10, -1, -1));

        setSize(new java.awt.Dimension(562, 556));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        PrintWriter pw = null;
        
        String strVrstica = "";
        String[] tabVrstica = null;
        char[] tabelaGeslo;
        String strGeslo = "";
        BufferedReader br = null;
        String strPreverjanje = "";
        String[] tabPreverjanje = null;
        boolean vpisan = false;
        String username = usrName.getText();

        tabelaGeslo = usrGeslo.getPassword();
        //tabelo znakov spremenimo v Strung
        for (int i = 0; i < tabelaGeslo.length; i++) {
            strGeslo = strGeslo + tabelaGeslo[i];
        }
        strGeslo = StaticVars.getMd5(strGeslo);

        try {
                 pw = new PrintWriter(new FileWriter("src/datoteke/uporabniki.txt", true));
            br = new BufferedReader(new FileReader("src/datoteke/uporabniki.txt"));
                
                while(br.ready()){
                strPreverjanje = br.readLine();
                tabPreverjanje = strPreverjanje.split(" ");
                if(tabPreverjanje[0].equals(username)){
                    vpisan = true;
                    break;
                }
                else{
                    vpisan = false;
                }
                
                }
                
                if(vpisan == false){
                strVrstica = strVrstica + usrName.getText() + " ";
                strVrstica = strVrstica + strGeslo + " ";
                strVrstica = strVrstica + nameTxt.getText() + " ";
                strVrstica = strVrstica + priimekTxt.getText()+ " ";
                strVrstica = strVrstica + 0;
                pw.println(strVrstica);
              
                }
                else{
                    JOptionPane.showMessageDialog(rootPane, "uporabniško ime že obstaja");
                }
                br.close();
                pw.close();
              
                
        } catch (IOException ioe) {
            Logger.getLogger(Registracija.class.getName()).log(Level.SEVERE, null, ioe);
        } finally {
            try {
                
                if (pw != null) {
                    pw.close();
                }
                if(br != null){
                    br.close();
                }
                 pocistiPolja();
            } catch (Exception e) {
                Logger.getLogger(Registracija.class.getName()).log(Level.SEVERE, null, e);
            }
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        dispose();
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnSpremeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSpremeniActionPerformed
     new SpremeniUpor().setVisible(true);
     dispose();
    }//GEN-LAST:event_btnSpremeniActionPerformed

    /**
     * @param args the command line arguments
     */
    private void pocistiPolja() {

        usrName.setText("");
        usrGeslo.setText("");
        nameTxt.setText("");
        priimekTxt.setText("");
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registracija.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registracija.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registracija.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registracija.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registracija().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSpremeni;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JTextField priimekTxt;
    private javax.swing.JPasswordField usrGeslo;
    private javax.swing.JTextField usrName;
    // End of variables declaration//GEN-END:variables
}
